export { default as AddCardDialog } from "./AddCardDialog"
export { default as ConfirmDialog } from "./ConfirmDialog"
export { default as EditionDialog } from "./EditionDialog"
export { default as TextDialog } from "./TextDialog"
export { default as CommentDialog } from "./CommentDialog"